// ============================================================
//  TALLY APP — CONFIGURATION
// ============================================================

const TALLY_CONFIG = {

  EVENT_NAME: 'Eurovision 2026 · Basel',

  COUNTRIES: [
    { flag: '🇩🇰', country: 'Denmark',        artist: 'Søren Torpegaard Lund',            song: 'Før Vi Går Hjem',    image: 'images/Denmark.webp'        },
    { flag: '🇩🇪', country: 'Germany',         artist: 'Sarah Engels',                     song: 'Fire',               image: 'images/Germany.webp'        },
    { flag: '🇮🇱', country: 'Israel',          artist: 'Noam Bettan',                      song: 'Michelle',           image: 'images/Israel.webp'         },
    { flag: '🇧🇪', country: 'Belgium',         artist: 'ESSYLA',                           song: 'Dancing on the Ice', image: 'images/Belgium.webp'        },
    { flag: '🇦🇱', country: 'Albania',         artist: 'Alis',                             song: 'Nân',                image: 'images/Albania.webp'        },
    { flag: '🇬🇷', country: 'Greece',          artist: 'Akylas',                           song: 'Ferto',              image: 'images/Greece.webp'         },
    { flag: '🇺🇦', country: 'Ukraine',         artist: 'LELÉKA',                           song: 'Ridnym',             image: 'images/Ukraine.webp'        },
    { flag: '🇦🇺', country: 'Australia',       artist: 'Delta Goodrem',                    song: 'Eclipse',            image: 'images/Australia.webp'      },
    { flag: '🇷🇸', country: 'Serbia',          artist: 'LAVINA',                           song: 'Kraj Mene',          image: 'images/Serbia.webp'         },
    { flag: '🇲🇹', country: 'Malta',           artist: 'AIDAN',                            song: 'Bella',              image: 'images/Malta.webp'          },
    { flag: '🇨🇿', country: 'Czechia',         artist: 'Daniel Zizka',                     song: 'CROSSROADS',         image: 'images/Czechia.webp'        },
    { flag: '🇧🇬', country: 'Bulgaria',        artist: 'DARA',                             song: 'Bangaranga',         image: 'images/Bulgaria.webp'       },
    { flag: '🇭🇷', country: 'Croatia',         artist: 'LELEK',                            song: 'Andromeda',          image: 'images/Croatia.webp'        },
    { flag: '🇬🇧', country: 'United Kingdom',  artist: 'LOOK MUM NO COMPUTER',             song: 'Eins, Zwei, Drei',   image: 'images/United Kingdom.webp' },
    { flag: '🇫🇷', country: 'France',          artist: 'Monroe',                           song: 'Regarde !',          image: 'images/France.webp'         },
    { flag: '🇲🇩', country: 'Moldova',         artist: 'Satoshi',                          song: 'Viva, Moldova!',     image: 'images/Moldova.webp'        },
    { flag: '🇫🇮', country: 'Finland',         artist: 'Linda Lampenius x Pete Parkkonen', song: 'Liekinheitin',       image: 'images/Finland.webp'        },
    { flag: '🇵🇱', country: 'Poland',          artist: 'ALICJA',                           song: 'Pray',               image: 'images/Poland.webp'         },
    { flag: '🇱🇹', country: 'Lithuania',       artist: 'Lion Ceccah',                      song: 'Sólo Quiero Más',    image: 'images/Lithuania.webp'      },
    { flag: '🇸🇪', country: 'Sweden',          artist: 'FELICIA',                          song: 'My System',          image: 'images/Sweden.webp'         },
    { flag: '🇨🇾', country: 'Cyprus',          artist: 'Antigoni',                         song: 'JALLA',              image: 'images/Cyprus.webp'         },
    { flag: '🇮🇹', country: 'Italy',           artist: 'Sal Da Vinci',                     song: 'Per Sempre Sì',      image: 'images/Italy.webp'          },
    { flag: '🇳🇴', country: 'Norway',          artist: 'JONAS LOVV',                       song: 'YA YA YA',           image: 'images/Norway.webp'         },
    { flag: '🇷🇴', country: 'Romania',         artist: 'Alexandra Căpitănescu',            song: 'Choke Me',           image: 'images/Romania.webp'        },
    { flag: '🇦🇹', country: 'Austria',         artist: 'COSMÓ',                            song: 'Tanzschein',         image: 'images/Austria.webp'        },
  ],

  // Fake jury scores for testing only.
  TEST_JURY_SCORES: {
    'Denmark':        52,
    'Germany':         0,
    'Israel':         14,
    'Belgium':        38,
    'Albania':        22,
    'Greece':        112,
    'Ukraine':        87,
    'Australia':      45,
    'Serbia':          2,
    'Malta':          18,
    'Czechia':        10,
    'Bulgaria':       27,
    'Croatia':        65,
    'United Kingdom': 198,
    'France':         22,
    'Moldova':        143,
    'Finland':        98,
    'Poland':         76,
    'Lithuania':      38,
    'Sweden':        238,
    'Cyprus':         58,
    'Italy':          32,
    'Norway':         76,
    'Romania':       155,
    'Austria':       176,
  },
};
